import React from "react";
import Head from "next/head";
import CollectionList from "../../components/collections/CollectionList";
import { shopifyClient, parseShopifyResponse } from "../../lib/shopify";

export default function collection({ collections }) {
  return (
    <div>
      <Head>
        <title>Collection</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <CollectionList collections={collections} />
      </main>
    </div>
  );
}
export const getServerSideProps = async () => {
  // Fetch all the products
  const collections = await shopifyClient.collection.fetchAll();

  return {
    props: {
      collections: parseShopifyResponse(collections),
    },
  };
};
